[package]
name = "mdular"
version = "0.1.0"
description = "A modular, local-first Markdown editor."
authors = ["CalebCao9420"]
license = "MIT"
repository = "https://github.com/CalebCao9420/mdular"
edition = "2021"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
sha2 = "0.10.9"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "=2.10.1"
tauri-plugin-dialog = "2"
minisign-verify = "=0.2.5"
